import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
 {
    _id: uuid(),
    title: "Sunglasses",
    image: "",
    price: 299,
    original_price: "₹ 699",
    discount: "50%",
    rating: 4.2,
    categoryName: "sunglasses",
  },
  {
    _id: uuid(),
    title: "Barware",
    image: "",
    price: 599,
    original_price: "₹ 899",
    discount: "50%",
    rating: 4.7,
    categoryName: "barware",
  },
  {
    _id: uuid(),
    title: "Grooming",
    image: "",
    price: 249,
    original_price: "₹599",
    discount: "50%",
    rating: 4.3,
    categoryName: "grooming",
  },
  {
    _id: uuid(),
    title: "Fitness",
    image: "",
    price: 999,
    original_price: "₹ 1199",
    discount: "50%",
    rating: 4,
    categoryName: "fitness",
  },
  {
    _id: uuid(),
    title: "Footwear",
    image: "",
    price: 1499,
    original_price: "₹ 1899",
    discount: "50%",
    rating: 3.8,
    categoryName: "footwear",
  },
  {
    _id: uuid(),
    title: "Wallets",
    image: "",
    price: 199,
    original_price: "₹ 449",
    discount: "50%",
    rating: 3.2,
    categoryName: "sunglasses",
  },
  {
    _id: uuid(),
    title: "Wallets",
    image: "",
    price: 749,
    original_price: "₹ 899",
    discount: "50%",
    rating: 3.5,
    categoryName: "barware",
  },
  {
    _id: uuid(),
    title: "Wallets",
    image: "",
    price: 799,
    original_price: "₹ 999",
    discount: "50%",
    rating: 3.1,
    categoryName: "grooming",
  },
  {
    _id: uuid(),
    title: "Wallets",
    image: "",
    price: 499,
    original_price: "₹ 899",
    discount: "50%",
    rating: 2.9,
    categoryName: "fitness",
  },
  {
    _id: uuid(),
    title: "Wallets",
    image: "",
    price: 399,
    original_price: "₹ 599",
    discount: "50%",
    rating: 2.7,
    categoryName: "footwear",
  },
  {
    _id: uuid(),
    title: "Wallets",
    image: "",
    price: 999,
    original_price: "₹ 1299",
    discount: "50%",
    rating: 2.5,
    categoryName: "footwear",
  },
  {
    _id: uuid(),
    title: "Wallets",
    image: "",
    price: 1399,
    original_price: "₹ 1499",
    discount: "50%",
    rating: 2.2,
    categoryName: "grooming",
  },
  {
    _id: uuid(),
    title: "Wallets",
    image: "",
    price: 649,
    original_price: "₹ 999",
    discount: "50%",
    rating: 2.1,
    categoryName: "barware",
  },
  {
    _id: uuid(),
    title: "Wallets",
    image: "",
    price: 1299,
    original_price: "₹ 1999",
    discount: "50%",
    rating: 4.6,
    categoryName: "fitness",
  },
  {
    _id: uuid(),
    title: "Wallets",
    image: "",
    price: 1099,
    original_price: "₹ 1499",
    discount: "50%",
    rating: 2.8,
    categoryName: "grooming",
  },
  {
    _id: uuid(),
    title: "Wallets",
    image: "",
    price: 899,
    original_price: "₹ 1199",
    discount: "50%",
    rating: 3.9,
    categoryName: "non-fiction",
  },

];
